# This dwm does not require any session manager so you can remove from this
# output (update-alternatives --config x-session-manager)
export _JAVA_AWT_WM_NONREPARENTING=1

# Laptop/Desktop specific start up
# $HOME/.vim/src/Sh/MacBookAir/FunctionKey.sh
$HOME/.vim/src/Sh/System/battery.sh &

### Start up program(s) ###

# Some introduction for the cpulimit and then statup
#The first variable is to set the number of cores in your processor. The reason
#that the number of cores is important is that you need to take it into
#consideration when setting cpulimit's -l option.  This is explained on the
#cpulimit project page (see http://cpulimit.sourceforge.net/):  "If your machine
#has one processor you can limit the percentage from 0% to 100%, which means
#that if you set for example 50%, your process cannot use more than 500 ms of
#cpu time for each second. But if your machine has four processors, percentage
#may vary from 0% to 400%, so setting the limit to 200% means to use no more
#than half of the available power."
NUM_CPU_CORES=$(nproc --all) #Automatically detects your system's number of CPU cores.


#evaluate the SSH agent , make sure before xprofile
export GPGKEY=8BA6E7ABD8112B3E
killall gpg-agent ssh-agent

# Make sure this is before the 'exec' command or it won't be sourced.
# Let make sure .profile use above defined variables
[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

# st , dwm, guake transparent
cpulimit -b -l $((10 * $NUM_CPU_CORES)) -- compton

# ~/Hubstaff/HubstaffClient.bin.x86_64 &
# ~/Applications/workcomposer-linux-installer.AppImage &
# keepassxc &
# ringcentral &
# remmina &
# anydesk &
/usr/local/bin/st -c vrkansagara-ide -n vrkansagara-ide -e vim $HOME/www &
# /usr/local/bin/st -c firle-explorer -n firle-explorer -e ranger $HOME/www &
# skype &
# thunderbird &
# clion &

# cpulimit -b -l $((5* $NUM_CPU_CORES)) -- slack
cpulimit -b -l $((5 * $NUM_CPU_CORES)) -- guake 
cpulimit -b -l $((5 * $NUM_CPU_CORES)) -- /usr/local/bin/st 2>&1 >> /tmp/dwm.log
cpulimit -b -l $((5 * $NUM_CPU_CORES)) -- /usr/local/bin/dwmblocks  2>&1 >> /tmp/dwm.log
cpulimit -b -l $((5 * $NUM_CPU_CORES)) -- thunar &
cpulimit -b -l $((5 * $NUM_CPU_CORES)) -- 1password &
# X window lock start ( compile slock if not)
# cpulimit -b -l $((5 * $NUM_CPU_CORES)) --  xautolock -time 2 -locker slock 2>&1 >> /tmp/dwm.lob

#Limit "teams" process to 20% CPU usage.
cpulimit -b -l $((20 * $NUM_CPU_CORES)) -- $HOME/Applications/Postman/Postman
# cpulimit -b -l $((20 * $NUM_CPU_CORES)) -- firefox
# cpulimit -b -l $((20 * $NUM_CPU_CORES)) -- teams

#Little heavier
cpulimit -b -l $((30 * $NUM_CPU_CORES)) -- google-chrome
cpulimit -b -l $((20 * $NUM_CPU_CORES)) -- ~/Applications/PhpStorm-213.7172.28/bin/phpstorm.sh

# Lets priority with nice
# nice -n 5 /snap/bin/phpstorm
# nice -n 10 /usr/bin/firefox

# DWM top bar using conky
# while true; do
#     (conky | while read LINE; do xsetroot -name "$LINE"; done)
#     sleep 1
# done&

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747465
/usr/lib/notification-daemon/notification-daemon &


# zsh/demnu clean cache
mkdir -p $HOME/old
mkdir -p $HOME/tmp
mv .bash* $HOME/old
mv $HOME/.cache/dmenu_run $HOME/old
mv .zcompdump-* $HOME/old

# Lets load arander configuration for the multiple window ( extended monitor(s))
[ -f "$HOME/.screenlayout/home.sh" ] && . "$HOME/.screenlayout/home.sh"
#[ -f "$HOME/.screenlayout/single.sh" ] && . "$HOME/.screenlayout/single.sh"

# set baground
WALLPAPERS="$HOME/git/vrkansagara/dwm/dwm/images"
while true; do
    find ${WALLPAPERS} -type f \( -iname \*.jpg -o -iname \*.png \) | shuf -n 1 | xargs feh --bg-fill
    # Lets wait for next image to load
    sleep  3m
done&


# Start Window Manager (Always last line)
# Log stderr to a file
# Instead of quiting dwm , make it hot reload(Will not disturb your stream while hot reload)
while true; do
    /usr/local/bin/dwm 2>&1 >> /tmp/dwm.log
    # Log stderr to a file
    # dwm 2> ~/.dwm.log
    # No error logging
    ##dwm >/dev/null 2>&1
done
